
# dbt project configuration file for evolving IEEE Fraud Detection analytics
# Defines project metadata, directory structure, and model configurations
# See https://docs.getdbt.com/reference/dbt_project.yml for details
name: 'my_dbt_project'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'my_dbt_project'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  my_dbt_project:
    staging:
      +database: IEEE_FRAUD_DETECTION
      +schema: staging

seeds:
  my_dbt_project:
    sample_train_identity:
      +column_types:
        TRANSACTIONID: integer
        ID_01: varchar(255)
        ID_02: varchar(255)
        ID_03: varchar(255)
        DEVICETYPE: varchar(100)
        DEVICEINFO: varchar(255)
    sample_train_transaction:
      +column_types:
        TRANSACTIONID: integer
        ISFRAUD: integer
        TRANSACTIONDT: integer
        TRANSACTIONAMT: float
        PRODUCTCD: varchar(50)
        CARD1: integer
        CARD2: integer
        CARD3: integer
        CARD4: varchar(50)
        CARD5: integer
        CARD6: varchar(50)
        ADDR1: integer
        ADDR2: integer

